Scripts
august-alt/gpui pull request #14
Opened 2022-11-16 06:00 UTC by AlexSP0

fix basescriptswidget, scriptswidget,  scriptspowershellwidget, scriptscommonslots, modelbuilder, scriptsmodelio

2023-01-18 06:37 UTC, august-alt requested changes

2023-01-18 06:37 UTC, august-alt commented on src/plugins/scripts/i18n/scripts_plugin_ru.ts
> +        <translation>При выходе из системы</translation>
Change Russian translation to: "Выход из системы"

2023-01-18 06:37 UTC, august-alt commented on src/plugins/scripts/i18n/scripts_plugin_ru.ts
> +        <translation>При загрузке компьютера</translation>
Change Russian translation to: "Запуск"

2023-01-18 06:37 UTC, august-alt commented on src/plugins/scripts/i18n/scripts_plugin_ru.ts
> +        <translation>При выключении компьютера</translation>
Change Russian translation to: "Завершение работы"

2023-01-18 06:37 UTC, august-alt commented on src/plugins/scripts/scriptitem.h
> +    //static inline const std::string PATH      = "path";
Remove comments.

2023-01-20 09:36 UTC, august-alt requested changes

2023-01-20 09:36 UTC, august-alt commented on src/plugins/scripts/scriptstreemodel.cpp
> +    userScripts->setProperty(ScriptsFolderItem::HELP_MSG, "Scripts for user");
Help message is not translated.

2023-01-20 09:36 UTC, august-alt commented on src/plugins/scripts/scriptstreemodel.cpp
> +    userSystemSetting->setProperty(ScriptsFolderItem::HELP_MSG, "System settings for user");
Help message is not translated.

2023-01-20 09:36 UTC, august-alt commented on src/plugins/scripts/scriptstreemodel.cpp
> +    machineScripts->setProperty(ScriptsFolderItem::HELP_MSG, "Scripts for computer");
Help message is not translated.

2023-01-20 09:36 UTC, august-alt commented on src/plugins/scripts/scriptstreemodel.cpp
> +    machineSystemSettings->setProperty(ScriptsFolderItem::HELP_MSG, "System settings for computer");
Help message is not translated.

2023-01-21 08:32 UTC, AlexSP0 commented on src/plugins/scripts/CMakeLists.txt
> +#file(GLOB_RECURSE TS_FILES ${CMAKE_CURRENT_SOURCE_DIR} *.ts)
fixed

2023-01-21 08:33 UTC, AlexSP0 commented on src/plugins/scripts/basescriptswidget.cpp
> +BaseScriptWidget::BaseScriptWidget(QWidget *p)
class renamed, inheritance already implemented

2023-01-21 08:33 UTC, AlexSP0 commented on src/plugins/scripts/scriptstreemodel.cpp
> +    userScripts->setProperty(ScriptsFolderItem::HELP_MSG, "Scripts for user");
fixed

2023-01-21 08:33 UTC, AlexSP0 commented on src/plugins/scripts/scriptstreemodel.cpp
> +    userSystemSetting->setProperty(ScriptsFolderItem::HELP_MSG, "System settings for user");
fixed

2023-01-21 08:33 UTC, AlexSP0 commented on src/plugins/scripts/scriptstreemodel.cpp
> +    machineScripts->setProperty(ScriptsFolderItem::HELP_MSG, "Scripts for computer");
fixed

2023-01-21 08:34 UTC, AlexSP0 commented on src/plugins/scripts/scriptstreemodel.cpp
> +    machineSystemSettings->setProperty(ScriptsFolderItem::HELP_MSG, "System settings for computer");
fixed

2023-03-03 11:17 UTC, august-alt requested changes
Refactoring of *BaseScriptTabWidget::findRootItem required. We need to provide additional fields in tree model, to simplify widget and model.

2023-03-03 11:18 UTC, august-alt commented
Additionally it would be preferable to cherry pick set of commits in separate branch instead of merging this whole branch.

2023-03-05 13:35 UTC, merged