CI improvements
august-alt/gpui pull request #36
Opened 2023-06-01 13:34 UTC by mchernigin

2023-06-06 22:09 UTC, august-alt requested changes
Summary:
- You need to describe why we need QEMU. 
- Also why do we need to rename all of workflows in this PR?
- We need to investigate if we need docker actions at all. 
- It will be better to pass uid and gid as variables instead of using hard-coded values.

2023-06-08 08:57 UTC, august-alt approved these changes

2023-06-08 09:12 UTC, august-alt approved these changes

2023-06-08 10:15 UTC, mchernigin commented
For now buildx is being used directly. If will be any need to use podman instead of docker, it should be as easy as `s/docker buildx build/podman build`

2023-06-09 08:39 UTC, merged